# Generated by Django 3.0.6 on 2020-05-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0004_microuser_crc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='crc',
            field=models.CharField(default='0x0', max_length=10, verbose_name='crc32'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='datastore',
            field=models.TextField(blank=True, default=''),
        ),
    ]
