# Generated by Django 3.2.6 on 2021-08-29 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0008_auto_20210828_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_no', models.CharField(max_length=40)),
                ('registration_date', models.DateField()),
                ('unit', models.CharField(choices=[('mo', 'Month'), ('hr', 'Hour')], max_length=2)),
                ('unit_rate', models.DecimalField(decimal_places=2, max_digits=16)),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='microinvoicer.fiscalentity')),
                ('registry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='microinvoicer.microregistry')),
            ],
        ),
    ]
