# Generated by Django 3.2.6 on 2021-08-29 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0009_servicecontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microregistry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registries', to=settings.AUTH_USER_MODEL),
        ),
    ]
