# Generated by Django 3.2.6 on 2021-08-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0010_alter_microregistry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecontract',
            name='currency',
            field=models.CharField(choices=[('eur', 'Euros'), ('usd', 'US Dollars'), ('ron', 'Lei')], default='eur', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicecontract',
            name='invoice_currency',
            field=models.CharField(choices=[('eur', 'Euros'), ('usd', 'US Dollars'), ('ron', 'Lei')], default='ron', max_length=3),
            preserve_default=False,
        ),
    ]
