# Generated by Django 3.2.6 on 2021-08-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0013_auto_20210829_1751_squashed_0016_auto_20210829_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.fiscalentity'),
        ),
        migrations.AlterField(
            model_name='timeinvoice',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.fiscalentity'),
        ),
        migrations.AlterField(
            model_name='timeinvoice',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.servicecontract'),
        ),
        migrations.AlterField(
            model_name='timeinvoice',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.fiscalentity'),
        ),
    ]
