# Generated by Django 3.2.7 on 2021-09-04 07:22

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0016_fill_invoice_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalentity',
            name='country',
            field=django_countries.fields.CountryField(default='RO', max_length=2),
        ),
    ]
