# Generated by Django 3.2.7 on 2021-09-04 09:00

from django.db import migrations
from django.db.migrations.operations.special import RunPython


def copy_seller_from_user(apps, schema_editor):
    MicroRegistry = apps.get_model("microinvoicer", "MicroRegistry")
    for registry in MicroRegistry.objects.all():
        seller_copy = registry.user.seller
        seller_copy.pk = None
        seller_copy.save()
        registry.seller = seller_copy
        registry.save()


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0019_microregistry_seller'),
    ]

    operations = [
        migrations.RunPython(copy_seller_from_user, reverse_code=RunPython.noop),
    ]
