# Generated by Django 3.2.7 on 2021-09-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0021_remove_microuser_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microregistry',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='microinvoicer.fiscalentity'),
        ),
    ]
