# Generated by Django 3.2.7 on 2021-09-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0024_alter_servicecontract_invoicing_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microuser',
            name='crc',
        ),
        migrations.RemoveField(
            model_name='microuser',
            name='datastore',
        ),
    ]
