# Generated by Django 4.1.1 on 2023-01-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microinvoicer", "0026_timeinvoice_attached_cost_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicecontract",
            name="unit",
            field=models.CharField(choices=[("mo", "Month"), ("d", "Day"), ("hr", "Hour")], max_length=2),
        ),
        migrations.AlterField(
            model_name="timeinvoice",
            name="attached_cost",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name="timeinvoice",
            name="attached_description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="timeinvoice",
            name="unit",
            field=models.CharField(choices=[("mo", "Month"), ("d", "Day"), ("hr", "Hour")], max_length=2),
        ),
    ]
