# Generated by Django 4.1.1 on 2023-01-05 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microinvoicer", "0029_microregistry_include_vat"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microregistry",
            name="include_vat",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
