# Generated by Django 4.1.5 on 2023-01-11 09:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0031_timeinvoice_include_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microregistry',
            name='include_vat',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Apply VAT (%)'),
        ),
    ]
