apiVersion: v1
kind: Service
metadata:
  name: micro-invoicer
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}

spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: "{{ .Release.Name }}-{{ .Values.useEnvironment }}"
