apiVersion: v1
kind: Service
metadata:
  name: micro-invoicer
  {{/* annotations: */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-name: "{{ .Release.Name }}-{{ .Values.useEnvironment }}.{{ .Values.useDomain }}" */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-protocol: "http" */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443" */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true" */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true" */}}

  {{/*   service.beta.kubernetes.io/do-loadbalancer-certificate-id: {{ .Values.sslCertificateId }} */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-hostname: "{{ .Release.Name }}-{{ .Values.useEnvironment }}.{{ .Values.useDomain }}" */}}
  {{/*   service.beta.kubernetes.io/do-loadbalancer-disable-lets-encrypt-dns-records: "false" */}}

spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    app: "{{ .Release.Name }}-{{ .Values.useEnvironment }}"
