# Generated by Django 3.0.6 on 2020-05-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0002_auto_20200319_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microuser',
            name='first_name',
            field=models.CharField(max_length=40, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='last name'),
        ),
    ]
