# Generated by Django 3.0.6 on 2020-05-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0003_auto_20200509_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='microuser',
            name='crc',
            field=models.CharField(default='', max_length=10, verbose_name='crc32'),
        ),
    ]
