# Generated by Django 3.2.6 on 2021-08-28 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0005_auto_20200509_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microuser',
            options={},
        ),
        migrations.AlterField(
            model_name='microuser',
            name='crc',
            field=models.CharField(default='0x0', max_length=10),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='microuser',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='MicroRegistry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=40)),
                ('invoice_series', models.CharField(max_length=16)),
                ('next_invoice_no', models.IntegerField(max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
