# Generated by Django 3.2.6 on 2021-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0006_auto_20210828_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microregistry',
            name='next_invoice_no',
            field=models.IntegerField(),
        ),
    ]
