# Generated by Django 3.2.6 on 2021-08-28 12:59
# Extension disabled
from django.db.migrations.operations.special import RunPython
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0007_alter_microregistry_next_invoice_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalEntity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner_fullname', models.CharField(max_length=255)),
                ('registration_id', models.CharField(max_length=40)),
                ('fiscal_code', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('bank_account', models.CharField(max_length=40)),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='microuser',
            name='seller',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='microinvoicer.fiscalentity'),
        ),
        migrations.RunPython(code=RunPython.noop, reverse_code=RunPython.noop)
    ]
