# Generated by Django 3.2.6 on 2021-08-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0014_timeinvoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinvoice',
            name='contract_registration_date',
        ),
        migrations.RemoveField(
            model_name='timeinvoice',
            name='contract_registration_no',
        ),
    ]
