# Generated by Django 3.2.6 on 2021-08-29 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0015_auto_20210829_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinvoice',
            name='contract',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.servicecontract'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timeinvoice',
            name='buyer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.fiscalentity'),
        ),
        migrations.AlterField(
            model_name='timeinvoice',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='microinvoicer.fiscalentity'),
        ),
    ]
