# Generated by Django 3.2.6 on 2021-09-02 19:46
from django.db.migrations.operations.special import RunPython
from django.db import migrations


def fill_descriptions(apps, schema_editor):
    TimeInvoice = apps.get_model("microinvoicer", "TimeInvoice")
    for invoice in TimeInvoice.objects.all():
        invoice.description = invoice.description or invoice.contract.invoicing_description
        invoice.save()

class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0015_import_invoices_from_datastore'),
    ]

    operations = [
        migrations.RunPython(fill_descriptions, reverse_code=RunPython.noop),
    ]
