# Generated by Django 3.2.7 on 2021-09-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0017_fiscalentity_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='invoicing_description',
            field=models.CharField(max_length=255, verbose_name='Service description template'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='registration_date',
            field=models.DateField(verbose_name='Contract date'),
        ),
        migrations.AlterField(
            model_name='servicecontract',
            name='registration_no',
            field=models.CharField(max_length=40, verbose_name='Contract number'),
        ),
    ]
