# Generated by Django 3.2.7 on 2021-09-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0023_alter_timeinvoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecontract',
            name='invoicing_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Service description template'),
        ),
    ]
