# Generated by Django 4.0.3 on 2022-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microinvoicer', '0025_auto_20210905_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeinvoice',
            name='attached_cost',
            field=models.DecimalField(decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='timeinvoice',
            name='attached_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
