# Generated by Django 4.1.1 on 2023-01-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microinvoicer", "0028_alter_fiscalentity_id_alter_microregistry_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="microregistry",
            name="include_vat",
            field=models.BooleanField(default=False),
        ),
    ]
