name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build . -t ghcr.io/${{ github.repository }}/micro-invoicer:test-main
        docker push ghcr.io/${{ github.repository }}/micro-invoicer:test-main

